### ISSUE TITLE
ERROR: BrowserError: Could not start the browser with 3 tries

### ISSUE THREAD

**Issue by alienbuild** [sitespeedio/coach#329]
I've made a node app using webcoach to return JSON data for a bunch of urls stored in a text file. Everything works fine on my windows pc but on unix I get the error:
**ERROR: BrowserError: Could not start the browser with 3 tries**
I've ensured both Chrome and Google are installed and up to date and nothing is blocking the browsers from what I can see. 

Full error can be seen here:
![error](https://user-images.githubusercontent.com/32590877/52505622-005acf80-2be4-11e9-9889-2775a7f235d5.png)

Repo for the app I created is here:
https://github.com/alienbuild/node-espionagex

Run with 'node app.js -u all'

**Comment by soulgalore** [comment]
Hi @alienbuild 
usually when it can't start it's a mismatch between Firefox/Geckodriver and Chrome/Chromedriver. Geckodriver/Chromedriver should automatically be installed by latest version, can you verify that you run a recent version of Firefox/Chrome?

Best
Peter

**Comment by soulgalore** [comment]
Latest released or latest in apt-get? :) 

```
google-chrome --version
firefox --version
```

Just want to verify :)

**Comment by soulgalore** [comment]
Else do you run --headless or do you use xvfb or do you have a screen on your machine?

**Comment by satyadityasharma** [comment]
@soulgalore @alienbuild I did the following and it helped me fix this issue hope this helps you.

- First, I downgraded the webcoach version to 3.4.0

- Then I downgraded my google-chrome version to 75.0.3770.100

- Then I passed --no-sandbox flag after exec -a "$0" "$HERE/chrome" "$@" <here> in /opt/google/chrome/google-chrome

That's it. :)

**Comment by leonardoraele** [comment]
@soulgalore Same issue here. I'm also running the latest versions of chrome and ss.io, running with `--headless` option, inside a `debian:buster-slim`-based docker container.

```
root@96e5b2015900:/app# google-chrome --version
Google Chrome 79.0.3945.88 
root@96e5b2015900:/app# firefox --version
XPCOMGlueLoad error for file /opt/firefox/libxul.so:
libdbus-glib-1.so.2: cannot open shared object file: No such file or directory
Couldn't load XPCOM.
root@96e5b2015900:/app# node_modules/.bin/sitespeed.io --version
11.9.3
```

Any idea?

```
[2019-12-21 00:21:26] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/app/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:85:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[2019-12-21 00:21:26] ERROR: No data to collect
[2019-12-21 00:21:29] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/app/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:85:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[2019-12-21 00:21:29] ERROR: No data to collect
[2019-12-21 00:21:22] INFO: Versions OS: linux 4.9.184-linuxkit nodejs: v11.15.0 sitespeed.io: 11.9.3 browsertime: 7.8.3 coach: 4.3.0
[2019-12-21 00:21:22] INFO: Running tests using Chrome - 2 iteration(s)
[2019-12-21 00:21:24] INFO: Browser failed to start, trying 2 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-21 00:21:25] INFO: Browser failed to start, trying 1 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-21 00:21:26] INFO: Browser failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-21 00:21:27] INFO: Browser failed to start, trying 2 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-21 00:21:28] INFO: Browser failed to start, trying 1 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-21 00:21:29] INFO: Browser failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-21 00:21:30] INFO: HTML stored in /app/config/reports/sitespeed.io/page_name_here
```

**Comment by soulgalore** [comment]
Hi @leonardoraele does it work with Firefox? Chromedriver is very picky with Chrome version, they need to match exact, wonder if that's the problem. What Chrome version are you using?

**Comment by leonardoraele** [comment]
I don't have firefox installed in this image. Can try it.

The installed google chrome version is 79.0.3945.88. How can I know what version it was supposed to be?

**Comment by leonardoraele** [comment]
@soulgalore The installed google chrome version is 79.0.3945.88. I don't have firefox installed in this image. How can I know what version of google chrome sitespeed.io expects?

**Comment by soulgalore** [comment]
Hi @leonardoraele if you are using the latest, its 79. The way to see it is which Chromedriver version: https://github.com/sitespeedio/browsertime/blob/master/package.json#L9

Are you run headless with xvfb does that work? 

Best
Peter

**Comment by leonardoraele** [comment]
@soulgalore Tried to run with xvfb, but got the same result.

```
> google-chrome --version
Google Chrome 79.0.3945.88
> sitespeed.io --version
11.9.3
```

```
> xvfb-run sitespeed.io https://www.github.com --headless
[2019-12-26 21:17:41] INFO: Versions OS: linux 4.9.184-linuxkit nodejs: v11.15.0 sitespeed.io: 11.9.3 browsertime: 7.8.3 coach: 4.3.0
[2019-12-26 21:17:41] INFO: Running tests using Chrome - 3 iteration(s)
[2019-12-26 21:17:42] INFO: Browser failed to start, trying 2 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-26 21:17:43] INFO: Browser failed to start, trying 1 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-26 21:17:44] INFO: Browser failed to start, trying 0 more time(s): unknown error: Chrome failed to start: exited abnormally
  (chrome not reachable)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
[2019-12-26 21:17:44] ERROR: BrowserError: Could not start the browser with 3 tries
    at SeleniumRunner.start (/app/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:85:13)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
[2019-12-26 21:17:44] ERROR: No data to collect
```

**Comment by leonardoraele** [comment]
Note: The issue only happens when using chrome. It works fine for me with `-b firefox`.

**Comment by vasilvestre** [comment]
I have the same issue on both docker distribution and npm package install

Google Chrome 118.0.5993.88 
Mozilla Firefox 118.0.2
webcoach 7.0.0

**Comment by soulgalore** [comment]
Hi @vasilvestre can you share how you run and what OS you are using so I can see if I can reproduce it?
Thanks

**Comment by vasilvestre** [comment]
I use both `webcoach https://www.domain.fr` and `docker run sitespeedio/coach:latest https://www.domain.fr/`

**Comment by soulgalore** [comment]
Ah sorry that is my fault, that image hasn't been built in ages. I try to redirect people to use sitespeed.io directly but I see that I haven't updated the readme (and some other docs).

**Comment by soulgalore** [comment]
I see. If you click the Coach tab in the sitespeed.io result, then you need to click the "show/hide details" button to see the extra information. I'll try to make that more visible in upcoming releases.

![coach](https://github.com/sitespeedio/coach/assets/540757/d27c65cf-9b0d-4640-bac8-2b2b90309e42)

**Comment by vasilvestre** [comment]
Ooooh thank you !
