### ISSUE TITLE
chrome failed to start

### ISSUE THREAD

**Issue by nvjacobo** [sitespeedio/coach#365]
I am trying to run coach with docker When i run it:

My setup 
- Docker version 20.10.5+dfsg1, build 55c4c88
- Debian bullseye

```
docker run sitespeedio/coach:6.0.0 https://www.sitespeed.io/
Unable to find image 'sitespeedio/coach:6.0.0' locally
6.0.0: Pulling from sitespeedio/coach
767fb6cc1b89: Already exists 
c917d9c558a3: Already exists 
6fef7dab6264: Already exists 
bd7950fd118d: Already exists 
97536a2ed27e: Already exists 
553b21971ad2: Already exists 
0dd68e81990d: Pull complete 
f49452044dd7: Downloading [========>                                          ]  72.57MB/452.4MB
f76c2533ecfc: Download complete 
84fdd8ee1f14: Download complete 
f8dd18d722de: Download complete 
03fe10cacad9: Download complete 
fb44057e82e8: Downloading [=================================>                 ]  53.86MB/79.97MB
8c3a187ca342: Downloading [============================================>      ]  71.46MB/79.76MB
1e94a19202f4: Waiting              f49452044dd7: Pull complete 
f76c2533ecfc: Pull complete 
84fdd8ee1f14: Pull complete 
f8dd18d722de: Pull complete 
03fe10cacad9: Pull complete 
fb44057e82e8: Pull complete 
8c3a187ca342: Pull complete 
1e94a19202f4: Pull complete 
7ba078f3b3f4: Pull complete 
Digest: sha256:9a5d03347c4bd24f7ec81ccde6d31d2c33ac81a9b370f7e716dc42a7466a2ec0
Status: Downloaded newer image for sitespeedio/coach:6.0.0
Google Chrome 87.0.4280.88 
Mozilla Firefox 84.0
[2021-05-01 07:12:55] INFO: Running tests using Chrome - 1 iteration(s)
[2021-05-01 07:12:55] INFO: chrome failed to start, trying 2 more time(s): Server terminated early with status 2
[2021-05-01 07:12:55] INFO: chrome failed to start, trying 1 more time(s): Server terminated early with status 2
[2021-05-01 07:12:55] INFO: chrome failed to start, trying 0 more time(s): Server terminated early with status 2
[2021-05-01 07:12:55] ERROR: BrowserError: Could not start chrome with 3 tries
    at SeleniumRunner.start (/usr/src/app/node_modules/browsertime/lib/core/seleniumRunner.js:86:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[2021-05-01 07:12:55] ERROR: No data to collect
Error running advice:  TypeError: Cannot read property '0' of undefined
    at Object.run (/usr/src/app/lib/index.js:84:47)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/usr/src/app/bin/webcoach.js:88:20)
(node:19) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, unlink '/coach/trace-1.json.gz'
(node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by soulgalore** [comment]
Hi @alexislefebvre let me update the README, good idea. The Docker containers in the Coach isn't updated so it's better to run Coach through sitespeed.io I'll add that later today.
