### ISSUE TITLE
Upgrading project is launching error and I don't know how to fix it.

### ISSUE THREAD

**Issue by fernandatenorio** [sitespeedio/coach#382]
Hi
I am creating my performance project, and I am using another project to be my baseline. The problem is that this base project is using speedio version 17.2 and coach version 5.1.1. In my project I upgraded to speedio 26.1 and coach 7.1.2, but I am getting the following exception. The script is able to navigate through the application under test, start measuring, take the screenshot in the final page fully charged, but I guess when it does the measure.stop(), the exception is launched. Also the coach peformance score is 0 and red. In addition, I am able to run my project in speedio version 17.2 and coach version 5.1.1. Do you have any clue what might be happening?

[2023-08-11 18:58:42] INFO: Start to measure "page performance"
[2023-08-11 18:58:42] INFO: Could not set cookie because the URL is unknown
[2023-08-11 18:58:49] INFO: Take after page complete check screenshot
[2023-08-11 18:58:50] INFO: Take cumulative layout shift screenshot
[2023-08-11 18:58:50] ERROR: Couldn't execute script named HIGHLIGHT_LS error:JavascriptError: javascript error: entry.sources is not iterable
  (Session info: headless chrome=81.0.4044.113)
[2023-08-11 18:58:50] ERROR: JavascriptError: javascript error: entry.sources is not iterable
  (Session info: headless chrome=81.0.4044.113)
  (Session info: headless chrome=81.0.4044.113)
    at Object.throwDecodedError (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/error.js:522:15)
    at parseHttpResponse (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:589:13)
    at Executor.execute (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/http.js:514:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.execute (/app/node_modules/sitespeed.io/node_modules/selenium-webdriver/lib/webdriver.js:740:17)
    at async SeleniumRunner.runScript (/app/node_modules/sitespeed.io/node_modules/browsertime/lib/core/seleniumRunner.js:397:22)
    at async Measure.collect (/app/node_modules/sitespeed.io/node_modules/browsertime/lib/core/engine/command/measure.js:417:7)

<img width="1134" alt="image" src="https://github.com/sitespeedio/coach/assets/13337748/91496990-b034-4cbb-bc5d-59376f9287c6">

**Comment by soulgalore** [comment]
Hi @fernandatenorio I think the problem is that Chromedriver (the webdriver that drivers Chrome( isn't compatible to your Chrome version (81). If you upgrade to a later Chrome version I think it will work.

Best
Peter

**Comment by fernandatenorio** [comment]
Hi thanks for answering me
My machine chrome version is Version 115.0.5790.170 (Official Build) (x86_64), and it is up to date. The 81 version I believe is the version of chrome of image of sitespeedio, right? How could I change the version 81 of chrome? Can I force this in my configs?
Although make sense this problem is caused due to incompatibility of versions, would the script run until the end even with this incompatibility? Because as I said, everything goes fine until the measure.stop().

Thanks in advance.

**Comment by soulgalore** [comment]
Hi @fernandatenorio can you show me how your run/start sitespeed.io? If you use the Docker containers, a new version always comes with the latest stable of Chrome/Edge/Firefox.

**Comment by fernandatenorio** [comment]
Yes, I use docker containers. I think the version 26.1 of speedio is using an old Chrome version.

**Comment by soulgalore** [comment]
Can you show me how you start the container and the full output log, thanks!

**Comment by fernandatenorio** [comment]
Hi, Sorry for the delay
I couldn't keep going with the upgrade, so I don't have more information. I guess we can close this issue, and whenever I continue the upgrade, and face the issue, I come back. Thanks anyway.
